### ISSUE TITLE
Issue identifying "GMT" timezone

### ISSUE THREAD

**Issue by ctcarino** [cronitorio/cronitor-cli#26]
chat support really is frustrating since it takes time for them to respond. (6 hours). we will be a potential paid customer but experiencing support is preventing us from proceeding.

here's my issue. Whenever i do cronitor discover, it gives an error that GMT timezone is not recognized
![Screenshot 2024-11-13 143418](https://github.com/user-attachments/assets/92101c19-e9a9-4f8a-82ca-c86838c24bbd)

I have already reinstalled cronitor because as per support, its an issue from your side but its still not fixed
![Screenshot 2024-11-13 144144](https://github.com/user-attachments/assets/a8ba341e-3dfa-43d9-89c8-fbaa25db5316)

**Comment by ctcarino** [comment]
@shaneharter 

here's the screenshot. i did: cronitor discover -v

![cronitor](https://github.com/user-attachments/assets/4540bda8-e394-4da0-8ae9-697a88505fb4)

**Comment by shaneharter** [comment]
Hi Clarence, thanks for following-up today, our development team has found the issue and applied an additional fix a few minutes ago. I can see this was a frustrating experience for you and I'm sorry we were not able to apply a fix and close this issue out faster. In the end, the fix failed because the developer applied it to a next-generation API endpoint that will soon replace the one you are hitting but it has not yet been deployed to all users. We are dogfooding it ourselves and so the developer on this task only fixed it in that new environment.
