### ISSUE TITLE
Cronitor for ARM?

### ISSUE THREAD

**Issue by santyf-dev** [cronitorio/cronitor-cli#7]
I see that the packages available for Cronitor only exist for amd64 (x86_64), on Windows, macOS and Linux. Is there any way to use Cronitor on ARM? I apply the question for Windows (ARM), macOS (Apple Silicon) and Linux (ARM), in general I would benefit Croniton on such a popular device for programming tasks as the Raspberry PI.

**Comment by tecncr** [comment]
Since the source code is available, you can get a binary on any of the platforms where the Go compiler is available.

Also, if you feel compiling is too Zzzzzzz, I have binaries specifically built for the Raspberry Pi (armhf) [here](https://ncastillo.xyz/utils/cronitor-cli-armhf)

Some screenshots of the compiling process:
![cronitor-cli-building-on-rpi1](https://user-images.githubusercontent.com/6446155/127402241-db88870f-1705-4c5a-82b9-dd573aa2b832.png)
![cronitor-cli-built-on-rpi1](https://user-images.githubusercontent.com/6446155/127402254-21459e0f-04e5-4259-b3d0-783e38c29da7.png)

If your Pi is running an aarch64 OS instead of armhf Raspbian, just let me know and I can compile it using my second RPi 4 running on aarch64 to save you some time ;)

Alternatively, _you can unblock me from Discord and let us be friends again 🥺🥺🥺
Santy enserio perdóname :( me humillo públicamente ante tí en este issue de GitHub para pedirte disculpa por lo que sea que haya pasado, volvamos a hablar, te extraño mucho :c_

**Comment by timeowilliams** [comment]
Hey @santyf-dev 

I'm using the new M1 chip that's ARM based and have no issues.

**Comment by agneevX** [comment]
I'd love this too, especially for `arm64`. 

> I'm using the new M1 chip that's ARM based and have no issues.

You're using Rosetta 2 probably.

**Comment by santyf-dev** [comment]
There a solution, is simple. Run "go build" in the cloned repository from source and there is Cronitor for you architecture (ARM in this case).

**Comment by shaneharter** [comment]
Hi there, I wanted to let you all know, we are now building ARM artifacts by default. For example:
https://github.com/cronitorio/cronitor-cli/releases/tag/28.0
